// <auto-generated />
using MVC_testovoe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_testovoe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230531071208_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_testovoe.Models.Izdel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Izdels");
                });

            modelBuilder.Entity("MVC_testovoe.Models.Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IzdelId")
                        .HasColumnType("bigint");

                    b.Property<long>("IzdelUpId")
                        .HasColumnType("bigint");

                    b.Property<int>("kol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IzdelId");

                    b.HasIndex("IzdelUpId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("MVC_testovoe.Models.Link", b =>
                {
                    b.HasOne("MVC_testovoe.Models.Izdel", "Izdel")
                        .WithMany()
                        .HasForeignKey("IzdelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_testovoe.Models.Izdel", "IzdelUp")
                        .WithMany()
                        .HasForeignKey("IzdelUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izdel");

                    b.Navigation("IzdelUp");
                });
#pragma warning restore 612, 618
        }
    }
}
